#!/usr/bin/env bash
[[ "${DEBUG,,}" == "true" ]] && set -x

echo "nameserver 209.222.18.222" > /etc/resolv.conf
echo "nameserver 209.222.18.218" >> /etc/resolv.conf

VPN_PORT="1197"
DEFAULT_RTABLE='lan'

DEFAULT_GW="$(ip route | grep 'default' | awk '{print $3}')"
DEFAULT_DEV="$(ip route | grep 'default' | awk '{print $5}')"
DEFAULT_SOURCE="$(ip addr show ${DEFAULT_DEV} | grep -m 1 -e 'inet\s' | awk '{print $2}' | sed 's/\/.*//')"
DEFAULT_NET="$(ip route | grep "dev ${DEFAULT_DEV}" | awk -v device="${DEFAULT_DEV}" '$3 == device {print $1}')"
DEFAULT_NET_SOURCE="$(ip route | grep "dev ${DEFAULT_DEV}" | awk -v device="${DEFAULT_DEV}" '$3 == device {print $9}')"

#loosen up rp_filter
for dev in /proc/sys/net/ipv4/conf/*; do echo 0 > ${dev}/rp_filter; done

echo 200 ${DEFAULT_RTABLE} >> /etc/iproute2/rt_tables
ip route add default via ${DEFAULT_GW} dev ${DEFAULT_DEV} src ${DEFAULT_SOURCE} table ${DEFAULT_RTABLE}
ip route add ${DEFAULT_NET} dev ${DEFAULT_DEV} src ${DEFAULT_NET_SOURCE} table ${DEFAULT_RTABLE}
ip rule add fwmark 1 table ${DEFAULT_RTABLE}


#MANGLE - PRE
iptables -t mangle -A PREROUTING -j CONNMARK --restore-mark
iptables -t mangle -A PREROUTING -m mark ! --mark 0 -j RETURN

#MANGLE - POST
iptables -t mangle -A POSTROUTING -j CONNMARK --save-mark

#NAT - POST
iptables -t nat -A POSTROUTING -o ${DEFAULT_DEV} -j SNAT --to-source ${DEFAULT_SOURCE}

#VPN
iptables -N VPN
iptables -A VPN -o tun+ -j ACCEPT
iptables -A VPN -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
iptables -A VPN -j DROP

#INPUT
iptables -A INPUT -i lo -j ACCEPT
#iptables -A INPUT -i tun+ -j VPN
iptables -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
#iptables -A INPUT -j LOG --log-prefix "INPUT: DROPPING: "

#OUTPUT
iptables -A OUTPUT -o lo -j ACCEPT
iptables -A OUTPUT -o tun+ -j VPN
#OUTPUT RULES
iptables -A OUTPUT -d 209.222.18.218/32 -p icmp -j ACCEPT
iptables -A OUTPUT -d 209.222.18.218/32 -p udp -m udp --dport 53 -j ACCEPT
iptables -A OUTPUT -d 209.222.18.218/32 -p tcp -m tcp --dport 53 -j ACCEPT
iptables -A OUTPUT -d 209.222.18.222/32 -p icmp -j ACCEPT
iptables -A OUTPUT -d 209.222.18.222/32 -p udp -m udp --dport 53 -j ACCEPT
iptables -A OUTPUT -d 209.222.18.222/32 -p tcp -m tcp --dport 53 -j ACCEPT
iptables -A OUTPUT -p tcp -m owner --cmd-owner openvpn -j ACCEPT 2>/dev/null &&
iptables -A OUTPUT -p udp -m owner --cmd-owner openvpn -j ACCEPT || {
    iptables -A OUTPUT -p tcp -m tcp --dport ${VPN_PORT} -j ACCEPT
    iptables -A OUTPUT -p udp -m udp --dport ${VPN_PORT} -j ACCEPT; }

#WebUi - Inbound
iptables -t mangle -A PREROUTING -p tcp -m tcp --dport 8443 -j MARK --set-mark 1
iptables -A INPUT -i eth0 -p tcp -m tcp --dport 8443 -j ACCEPT
iptables -A OUTPUT ! -o tun+ -p tcp -m tcp --sport 8443 -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT

#RSYNC - Outbound
iptables -t mangle -A OUTPUT -p tcp -m tcp --dport 873 -j MARK --set-mark 1
iptables -A OUTPUT ! -o tun+ -p tcp -m tcp --dport 873 -j ACCEPT