#!/bin/bash

mkdir -p /dev/net

[[ -c /dev/net/tun ]] || mknod -m 0666 /dev/net/tun c 10 200

COUNT=0
while true; do

    VPN_SERVER="$(eval echo "\$OPENVPN_${COUNT}_SERVER")"
    VPN_OPTIONS="$(eval echo "\$OPENVPN_${COUNT}_OPTIONS")"

    if [[ -z "${VPN_SERVER}" ]]; then

        [[ "${COUNT}" == "0" ]] && exit 1

        wait -n

        killall openvpn || exit 1

        wait

        COUNT=0

    else

        exec sg vpn -c "openvpn --config /etc/openvpn/vpn.conf ${VPN_OPTIONS} --remote ${VPN_SERVER}" &

        sleep 10

        (( COUNT++ ))

    fi

done